### ISSUE TITLE
Code is not working ....!!! Please help me Out

### ISSUE THREAD

**Issue by nishant4uagr** [krupanss/Market-Basket-Analysis-R#1]
subset.matrix[lower.tri(subset.matrix, diag = TRUE)] <- NA

Above code is not working. Please correct it. Following is the error.

Warning message:
In `[<-`(`*tmp*`, as.vector(i), value = NA) :
  x[.] <- val: x is “ngTMatrix”, val not in {TRUE, FALSE} is coerced; NA |--> TRUE.

Please help me out. Please do the needful

**Comment by krupanss** [comment]
Updated the code part while creating subset. Add sparse = FALSE as below.
subset.matrix <- is.subset(products.apriori, products.apriori, sparse = FALSE)

**Comment by nishant4uagr** [comment]
Should I add code like this ?


subset.matrix <- is.subset(products.apriori, products.apriori)
sparse = FALSE
subset.matrix <- is.subset(products.apriori, products.apriori, sparse = FALSE)
subset.matrix[lower.tri(subset.matrix, diag=T)] <- NA
redundant <- colSums(subset.matrix, na.rm=T) >= 1

**Comment by krupanss** [comment]
Yes.

**Comment by nishant4uagr** [comment]
subset.matrix <- is.subset(products.apriori, products.apriori, sparse = FALSE)

So we are just adding above code and remaining code will be as it is....
